### ISSUE TITLE
Notebook Imagestream without tags breaks JupyterHub spawner

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/jupyterhub-odh#112]
**Describe the bug**
Creating a blank imagestream without any tags in it makes Jupyterhun spawner  

**To Reproduce**
1. Submit an imagestream manifest
2. Open JH spawner
3. See that no images are found

**Expected behavior**
Imagestream is skipped

**Screenshots**
```
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: test
    opendatahub.io/notebook-image-url: test
  name: test
  labels:
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
```
Produces:
![image](https://user-images.githubusercontent.com/7453394/130104845-dcfc2d05-e481-4a99-bc8f-7898888c42ce.png)

Deleting the imagestream restores correct behavior.

**Additional context**
n/a
